name: PlayerLocater
version: 1.3
author: Zen Wolf
main: me.zenisbestwolf.playerlocater.Main
description: Find out where a player is with a command.
default: op
api-version: 1.15
permissions:
    playerlocater.locate:
        description: "Allows players to use /whereis"
        default: op
commands:
    whereis:
        aliases: [donde]
        description: Locates the specified player.
        usage: "/<command> [target]"
        permission: playerlocater.locate